### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by dcore94** [vincentml/schematron-basex#2]
After installing the xar in BaseX8.5.3 I try to run the code of the first example and I get the following error:

Stopped at /.../basex853/repo/http-github.com-vincentml-schematron-basex-1.0/content/schematron.xqm, 39/31:
[FODC0002] Resource 'iso-schematron/iso_dsdl_include.xsl' does not exist.

I need to soft-link the directory containing the stylesheets into the directory containing the examples to get it run. 
Should this be resolved automatically instead?

**Comment by vincentml** [comment]
Thank you for reporting this problem. I have reproduced this error message in BaseX 8.5.3, and confirmed that this error does not occur in BaseX 8.2.3. My next step will be to determine more specifically where the problem began.

**Comment by vincentml** [comment]
This problem is fixed. Please update to version 1.1. If you still have trouble let me know.

**Comment by dcore94** [comment]
Nice. Thanks!
